### ISSUE TITLE
Enforcing local accounts or groups in Privilege Rights is not idempotent

### ISSUE THREAD

**Issue by Andy-Adrian** [ayohrling/local_security_policy#113]
Trying to set 
```yaml
---
local_security_policy::policies:
  'Act as part of the operating system':
    ensure: present
    policy_value: 'APPServices,lsp_admin,*S-1-5-32-544'
```
successfully changes the setting, but is not idempotent.

```
PS C:\temp> puppet apply -e 'include local_security_policy'
Notice: Compiled catalog for win2019.home.local in environment production in 0.12 seconds
Notice: /Stage[main]/Local_security_policy/Local_security_policy[Act as part of the operating system]/policy_value: policy_value changed 'APPServices,lsp_admin,*S-1-5-32-544' to '*S-1-5-32-544,*S-1-5-21-646623468-1599700546-2380620256-1001,*S-1-5-21-646623468-1599700546-2380620256-500'
Notice: Applied catalog in 0.37 seconds
```
